// default package
// Generated 2013/07/04 18:23:10 by Hibernate Tools 3.4.0.CR1
package edu.leo.dao.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MSystem generated by hbm2java
 */
@Entity
@Table(name = "m_system", catalog = "SSHAnnotationSample2")
public class MSystem implements java.io.Serializable {

    private String sysKey;
    private String sysVal;
    private String description;
    private Date insDate;
    private String insUserId;
    private Date updDate;
    private String updUserId;
    private Date delDate;
    private String delUserId;
    private String delFlg;
    private Long updCnt;

    public MSystem() {
    }

    public MSystem(String sysKey) {
        this.sysKey = sysKey;
    }

    public MSystem(String sysKey, String sysVal, String description, Date insDate, String insUserId, Date updDate, String updUserId, Date delDate, String delUserId, String delFlg, Long updCnt) {
        this.sysKey = sysKey;
        this.sysVal = sysVal;
        this.description = description;
        this.insDate = insDate;
        this.insUserId = insUserId;
        this.updDate = updDate;
        this.updUserId = updUserId;
        this.delDate = delDate;
        this.delUserId = delUserId;
        this.delFlg = delFlg;
        this.updCnt = updCnt;
    }

    @Id
    @Column(name = "sys_key", unique = true, nullable = false, length = 100)
    public String getSysKey() {
        return this.sysKey;
    }

    public void setSysKey(String sysKey) {
        this.sysKey = sysKey;
    }

    @Column(name = "sys_val", length = 4000)
    public String getSysVal() {
        return this.sysVal;
    }

    public void setSysVal(String sysVal) {
        this.sysVal = sysVal;
    }

    @Column(name = "description", length = 256)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ins_date", length = 19)
    public Date getInsDate() {
        return this.insDate;
    }

    public void setInsDate(Date insDate) {
        this.insDate = insDate;
    }

    @Column(name = "ins_user_id", length = 20)
    public String getInsUserId() {
        return this.insUserId;
    }

    public void setInsUserId(String insUserId) {
        this.insUserId = insUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "upd_date", length = 19)
    public Date getUpdDate() {
        return this.updDate;
    }

    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }

    @Column(name = "upd_user_id", length = 20)
    public String getUpdUserId() {
        return this.updUserId;
    }

    public void setUpdUserId(String updUserId) {
        this.updUserId = updUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "del_date", length = 19)
    public Date getDelDate() {
        return this.delDate;
    }

    public void setDelDate(Date delDate) {
        this.delDate = delDate;
    }

    @Column(name = "del_user_id", length = 20)
    public String getDelUserId() {
        return this.delUserId;
    }

    public void setDelUserId(String delUserId) {
        this.delUserId = delUserId;
    }

    @Column(name = "del_flg", length = 1)
    public String getDelFlg() {
        return this.delFlg;
    }

    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    @Column(name = "upd_cnt", precision = 18, scale = 0)
    public Long getUpdCnt() {
        return this.updCnt;
    }

    public void setUpdCnt(Long updCnt) {
        this.updCnt = updCnt;
    }

}
