// default package
// Generated 2013/07/03 14:17:38 by Hibernate Tools 3.4.0.CR1
package edu.leo.dao.entity;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TContactsPhone generated by hbm2java
 */
@Entity
@Table(name = "t_contacts_phone", catalog = "SSHAnnotationSample2")
public class TContactsPhone implements java.io.Serializable {

    private TContactsPhoneId id;
    private String phoneLabel;
    private String phoneNumber;
    private Date insDate;
    private String insUserId;
    private Date updDate;
    private String updUserId;
    private Date delDate;
    private String delUserId;
    private String delFlg;
    private Long updCnt;

    public TContactsPhone() {
    }

    public TContactsPhone(TContactsPhoneId id) {
        this.id = id;
    }

    public TContactsPhone(TContactsPhoneId id, String phoneLabel, String phoneNumber, Date insDate, String insUserId, Date updDate, String updUserId, Date delDate, String delUserId, String delFlg, Long updCnt) {
        this.id = id;
        this.phoneLabel = phoneLabel;
        this.phoneNumber = phoneNumber;
        this.insDate = insDate;
        this.insUserId = insUserId;
        this.updDate = updDate;
        this.updUserId = updUserId;
        this.delDate = delDate;
        this.delUserId = delUserId;
        this.delFlg = delFlg;
        this.updCnt = updCnt;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "contactsSeq", column = @Column(name = "contacts_seq", nullable = false, precision = 18, scale = 0)), @AttributeOverride(name = "phoneType", column = @Column(name = "phone_type", nullable = false, length = 2)) })
    public TContactsPhoneId getId() {
        return this.id;
    }

    public void setId(TContactsPhoneId id) {
        this.id = id;
    }

    @Column(name = "phone_label", length = 20)
    public String getPhoneLabel() {
        return this.phoneLabel;
    }

    public void setPhoneLabel(String phoneLabel) {
        this.phoneLabel = phoneLabel;
    }

    @Column(name = "phone_number", length = 11)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ins_date", length = 19)
    public Date getInsDate() {
        return this.insDate;
    }

    public void setInsDate(Date insDate) {
        this.insDate = insDate;
    }

    @Column(name = "ins_user_id", length = 20)
    public String getInsUserId() {
        return this.insUserId;
    }

    public void setInsUserId(String insUserId) {
        this.insUserId = insUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "upd_date", length = 19)
    public Date getUpdDate() {
        return this.updDate;
    }

    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }

    @Column(name = "upd_user_id", length = 20)
    public String getUpdUserId() {
        return this.updUserId;
    }

    public void setUpdUserId(String updUserId) {
        this.updUserId = updUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "del_date", length = 19)
    public Date getDelDate() {
        return this.delDate;
    }

    public void setDelDate(Date delDate) {
        this.delDate = delDate;
    }

    @Column(name = "del_user_id", length = 20)
    public String getDelUserId() {
        return this.delUserId;
    }

    public void setDelUserId(String delUserId) {
        this.delUserId = delUserId;
    }

    @Column(name = "del_flg", length = 1)
    public String getDelFlg() {
        return this.delFlg;
    }

    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    @Column(name = "upd_cnt")
    public Long getUpdCnt() {
        return this.updCnt;
    }

    public void setUpdCnt(Long updCnt) {
        this.updCnt = updCnt;
    }

}
